### ISSUE TITLE
Cell 커스텀클래스 만들기

### ISSUE THREAD

**Issue by TTOzzi** [codesquad-memeber-2020/photos-1#3]
- [x] Cell 을 처리하기 위한 커스텀클래스 만들기
- [x] Cell 크기 100 x 100 으로 변경
- [x] Cell 에 UIImageView 추가
- [x] Cell 의 UIImageView 가 Cell 을 가득 채우도록 설정

**Comment by TTOzzi** [comment]
ed50acaca94cc18103e8ffe234b75c2b21a2857f
e4ecce2d12b59ba38daa5096f31180fbac69ad70
b3219ca270b3b32d25a95c8f88643b37a8d4945e

**Comment by MagnaPax** [comment]
4b29b8716d0e538e01418cce57f5c9a8ec4c07ae
2c67d85befc735b9ce91deefdb6919646a690c54
